# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/aocutils',
                'doc_host': 'https://jvanelteren.github.io',
                'git_url': 'https://github.com/jvanelteren/aocutils',
                'lib_path': 'aocutils'},
  'syms': {'aocutils\\core': {'aocutils\\core.foo': ('core.html#foo', 'aocutils\\core.py')}}}