# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://jvanelteren.github.io/aocutils"

git_url = "https://github.com/jvanelteren/aocutils"

def custom_doc_links(name): return None
